<a href="https://colab.research.google.com/github/bttrung/python-study/blob/master/numpy/1_Creating_and_Saving_Numpy_ndarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

x = np.array([1,2,3,4,5])

In [2]:
x

array([1, 2, 3, 4, 5])

In [3]:
type(x)

numpy.ndarray

In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(5,)

In [0]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])

In [15]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [16]:
y.shape

(4, 3)

In [17]:
y.size

12

In [18]:
y.dtype

dtype('int64')

In [0]:
z = np.array(["hello", "world"])

In [20]:
z

array(['hello', 'world'], dtype='<U5')

In [0]:
a = np.array([1, 2.2, 3])

In [23]:
a

array([1. , 2.2, 3. ])

In [24]:
a.dtype

dtype('float64')

In [0]:
np.save("my_arr", y)

In [0]:
saved = np.load("my_arr.npy")

In [33]:
saved

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])