<a href="https://colab.research.google.com/github/bttrung/python-study/blob/master/numpy/2_Using_built_in_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# create numpy array from list
li = [1, 2, 3, 4, 5]
np.array(li)

array([1, 2, 3, 4, 5])

## zeros

In [5]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros((4, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.zeros((4, 5), dtype=str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [8]:
np.zeros((4, 5), dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ones

In [10]:
np.ones((3, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## full

In [11]:
np.full((4, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

## eye

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## diag

In [13]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

## arange

In [14]:
# generate interger array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(2, 9) # start, stop

array([2, 3, 4, 5, 6, 7, 8])

In [19]:
np.arange(2, 20, 3) # start, stop, step

array([ 2,  5,  8, 11, 14, 17])

## linspace

In [28]:
# generate non-integer array
np.linspace(0, 100, 10) # start, stop, how many?

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [29]:
np.linspace(0, 10, 20, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## reshape

In [32]:
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
np.reshape(x, (10, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
np.arange(50).reshape((5,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [43]:
np.linspace(0,1,24, endpoint=False).reshape((6,4))

array([[0.        , 0.04166667, 0.08333333, 0.125     ],
       [0.16666667, 0.20833333, 0.25      , 0.29166667],
       [0.33333333, 0.375     , 0.41666667, 0.45833333],
       [0.5       , 0.54166667, 0.58333333, 0.625     ],
       [0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333]])

## random

In [46]:
# generate random from 0 to 10, then reshape
np.random.randint(0,10,(3,4))

array([[9, 5, 2, 5],
       [3, 0, 5, 6],
       [2, 4, 3, 7]])

In [51]:
np.random.random((3, 5))

array([[0.17140834, 0.23798421, 0.88106218, 0.88037076, 0.13457177],
       [0.16156142, 0.51012353, 0.91492657, 0.35087652, 0.44239173],
       [0.24969397, 0.41854493, 0.59265646, 0.59790526, 0.65131386]])

In [52]:
np.random.normal(0,0.1,size=(5, 5))

array([[-0.02744904,  0.15090447,  0.06029131, -0.15580469, -0.02435312],
       [ 0.07607114, -0.06713584, -0.05054999, -0.0155895 ,  0.13553908],
       [-0.03320373,  0.15144214, -0.080544  ,  0.05336946,  0.0627936 ],
       [-0.21418096, -0.15342315,  0.1050102 , -0.12886968, -0.06969869],
       [-0.12371126, -0.01250216, -0.21097239, -0.06315301,  0.01672948]])

In [53]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [54]:
x.max()

99

In [55]:
x.min()

0

In [56]:
x.mean()

49.5

In [60]:
x.shape

(100,)

In [61]:
type(x)

numpy.ndarray