<a href="https://colab.research.google.com/github/bttrung/python-study/blob/master/numpy/3_Access%2C_Delete_and_Insert_elements_into_ndarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## access

In [0]:
x = np.array([1,2,3,4,5])

In [4]:
x[0]

1

In [5]:
x[-1]

5

In [0]:
x[0] = 8

In [7]:
x

array([8, 2, 3, 4, 5])

In [15]:
z = np.arange(1, 28).reshape(3,3,3)
z

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [16]:
z[0,0,0]

1

In [17]:
z[0,1,0]

4

In [18]:
z[0,0,1]

2

In [19]:
z[1,0,0]

10

In [20]:
z.shape

(3, 3, 3)

## delete

In [33]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x = np.delete(x, [1, 4]) # delete index 0 and 4
x

array([0, 2, 3, 5, 6, 7, 8, 9])

In [40]:
v = np.arange(1,10).reshape(3, 3)
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
v = np.delete(v,1,axis=0) # delete row index=1
v

array([[1, 2, 3],
       [7, 8, 9]])

In [42]:
v = np.arange(1,10).reshape(3, 3)
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
v = np.delete(v,0,axis=1) # delete column index=0
v

array([[2, 3],
       [5, 6],
       [8, 9]])

In [44]:
v = np.arange(1,10).reshape(3, 3)
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
v = np.delete(v,[1,2],axis=1) # delete 2 columns index=1,2
v

array([[1],
       [4],
       [7]])

## append

In [52]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x = np.append(x, 10)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
x = np.append(x, [22, 33])

In [55]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 22, 33])

In [65]:
v = np.arange(1,13).reshape(3, 4)
v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
v = np.append(v, [[11,22,33, 44]], axis=0) # append more row
v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44]])

In [68]:
v = np.append(v, [[1],[2],[3],[4]], axis=1) # append more column
v

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  2],
       [ 9, 10, 11, 12,  3],
       [11, 22, 33, 44,  4]])

## insert

In [70]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x = np.insert(x, 2, [33, 44])
x

array([ 1,  2, 33, 44,  3,  4,  5,  6,  7,  8,  9])

In [79]:
z = np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
z = np.insert(z, 1, [7,8,9], axis=0) # insert 1 row to index 1
z

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [81]:
z = np.insert(z, 0, [11,22,33], axis=1)
z

array([[11,  1,  2,  3],
       [22,  7,  8,  9],
       [33,  4,  5,  6]])