<a href="https://colab.research.google.com/github/bttrung/python-study-notebooks/blob/master/numpy/4_Slicing_ndarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## 1D array

In [3]:
# array[start:end]
# array[start:]
# array[:end]

x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[1:5]

array([2, 3, 4, 5])

In [5]:
x[4:]

array([5, 6, 7, 8, 9])

In [6]:
x[:4]

array([1, 2, 3, 4])

## Multi D arrays

In [9]:
z = np.arange(1,21).reshape(4,5)
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
z[1:4,2:5]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [12]:
z[0:,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [13]:
z[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [14]:
z[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [16]:
z[1:2,:]

array([[ 6,  7,  8,  9, 10]])

In [17]:
z[:,1]

array([ 2,  7, 12, 17])

In [18]:
z[2,:]

array([11, 12, 13, 14, 15])

## Notes: any changing on the result array will be affected to the original arary

In [20]:
c = z[:,3]
c

array([ 4,  9, 14, 19])

In [22]:
c[3] = 500
c

array([  4,   9,  14, 500])

In [24]:
# z also be impacted
z

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18, 500,  20]])

## Using copy function to resolve this problem

In [26]:
c = z[:,3].copy()
c

array([  4,   9,  14, 500])

In [28]:
c[3] = 1000
c

array([   4,    9,   14, 1000])

In [30]:
# z will be safe
z

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18, 500,  20]])

## diag

In [31]:
np.diag(z)

array([  1,   7,  13, 500])

In [32]:
np.diag(z, k=-1)

array([ 6, 12, 18])

In [33]:
np.diag(z, k=1)

array([ 2,  8, 14, 20])

In [34]:
np.diag(z, k=2)

array([ 3,  9, 15])

In [35]:
np.diag(z, k=3)

array([ 4, 10])

## find unique elements

In [36]:
np.unique(z)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  20, 500])