<a href="https://colab.research.google.com/github/bttrung/python-study-notebooks/blob/master/numpy/5_Boolean_Indexing%2C_Set_Operations_and_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
x[ x> 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
x[x <= 5]

array([0, 1, 2, 3, 4, 5])

In [8]:
x[(x >= 10) & (x < 15)]

array([10, 11, 12, 13, 14])

In [10]:
# assignment based on condition
x[(x >= 10) & (x < 15)] = -1
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-1, -1, -1, -1, -1],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 2, 4])

In [12]:
np.intersect1d(a, b)

array([2, 4])

In [13]:
np.setdiff1d(a, b)

array([1, 3, 5])

In [14]:
np.setdiff1d(b, a)

array([6, 7, 8])

In [15]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8])

## sort

In [18]:
c = np.random.randint(1, 20, size=(10,))
c

array([ 5, 13,  8,  7, 12, 12, 14,  7,  7, 18])

In [21]:
print(np.sort(c))
print(c)

[ 5  7  7  7  8 12 12 13 14 18]
[ 5 13  8  7 12 12 14  7  7 18]


In [23]:
# sort by method itself will also change the origional array
print(c.sort())
print(c)

None
[ 5  7  7  7  8 12 12 13 14 18]


## sort multi-d arrays

In [26]:
m = np.random.randint(1,9, size=(5, 6))
m

array([[8, 8, 2, 4, 5, 1],
       [1, 2, 1, 1, 6, 4],
       [6, 6, 1, 1, 6, 4],
       [7, 1, 5, 1, 3, 1],
       [2, 5, 6, 2, 3, 4]])

In [27]:
np.sort(m, axis=0)

array([[1, 1, 1, 1, 3, 1],
       [2, 2, 1, 1, 3, 1],
       [6, 5, 2, 1, 5, 4],
       [7, 6, 5, 2, 6, 4],
       [8, 8, 6, 4, 6, 4]])

In [28]:
np.sort(m, axis=1)

array([[1, 2, 4, 5, 8, 8],
       [1, 1, 1, 2, 4, 6],
       [1, 1, 4, 6, 6, 6],
       [1, 1, 1, 3, 5, 7],
       [2, 2, 3, 4, 5, 6]])